### ISSUE TITLE
Add Feature for better UX

### ISSUE THREAD

**Issue by kavin25** [Pictarine/macos-snippets#1]
Hey! This is more of a feature for better UX than an issue. 

I would love to see, if you could add icons for folders based on older name

 - Like Javascript gets JS logo, 
 - Python gets its logo, stuff like that.

 Unfortunately I am not a swift developer. I develop for web and have no idea how swift works, but I hope you could do something like that, like we see in **VS Code Material Icon Theme**

https://codespace.app/?ref=producthunt
The above link redirects to an app similar to yours which has this feature. But, the problem is, it's **paid**. And, I really don't want to spend money on this.
Love that you guys, are not doing that, that's why I would love this to happen

**Comment by marshallino16** [comment]
Hi, 

Sure, I'll see what I can do 👌

**Comment by marshallino16** [comment]
Hi @kavin25,

I've integrated some atom file icons and I'm currently working on a folder icon selection but it will not be included in v1.3.0.

<img width="1385" alt="Screen Shot 2020-10-06 at 3 06 30 PM" src="https://user-images.githubusercontent.com/1506323/95206476-094fda00-07e7-11eb-9779-40ed262cc8e1.png">

**Comment by kavin25** [comment]
Nice. How do I get to use this?

**Comment by marshallino16** [comment]
Install the app update available on the AppStore (link in README)

**Comment by kavin25** [comment]
Ok. Thanks for the update

**Comment by kavin25** [comment]
Looks pretty good now. Thanks a lot
