### ISSUE TITLE
UX Request: Right-click "Add Snippet" opens folder by default, rather than closing it

### ISSUE THREAD

**Issue by geochronology** [Pictarine/macos-snippets#10]
Right now if I right-click on a folder and select "Add snippet" it closes the folder by default. (If the folder is already closed, it remains closed.)

When I create a new snippet in a folder I do so with the intention of renaming and then editing it. In both cases it would be more helpful to have the folder state as open by default when I add snippet.

**Comment by marshallino16** [comment]
Hey,

It will be the case in the next update with all big sur / Xcode12.2 migration changes.

**Comment by marshallino16** [comment]
Version 1.5.0 is out

https://github.com/Pictarine/macos-snippets/releases/tag/v1.5.0
