### ISSUE TITLE
Welcome screen can be dragged like a pager

### ISSUE THREAD

**Issue by dagronf** [Pictarine/macos-snippets#13]
Hi there,

Just installed Snip from the App Store, and noticed that the welcome dialog has a weird dragging behaviour.  You can see the behaviour in the video I captured :-

https://www.dropbox.com/s/y4mcyxle8eyp7lb/snip-bug.mov?dl=0

A static image here :-

https://www.dropbox.com/s/o24zzmlq1cedmg8/snip-clip.png?dl=0

It seems like the welcome screen wants to be a pager.  Note that the dragging behaviour only happens when you drag on text.  I was trying to drag the welcome screen around and managed to trigger it.

**Comment by marshallino16** [comment]
Hi, 

Congratulation, you found something I never finished 😬

The idea here was to give a list of keyboard shortcuts for the editor. 

I guess I forgot to remove the pager code. 

🙏

**Comment by marshallino16** [comment]
Commit [18b547](https://github.com/Pictarine/macos-snippets/commit/f18b547d4f43c665df8b3c1c542f09197ccedec2) will fix that.

**Comment by dagronf** [comment]
Thanks mate.  Fantastic work!
