### ISSUE TITLE
"+" is not enough visible

### ISSUE THREAD

**Issue by jfx** [Pictarine/macos-snippets#14]
Hello,
the New snippet/New folder button is probably not enough visible for the first usage.

**Comment by marshallino16** [comment]
Hi, 

100% true. I'm trying to find a new way to have this "+" button.

**Comment by marshallino16** [comment]
Next version is fixing this issue. 

<img width="1307" alt="Screen Shot 2021-03-04 at 12 00 18" src="https://user-images.githubusercontent.com/1506323/109954138-3f837e00-7ce1-11eb-973b-7a9d7e40f782.png">

**Comment by marshallino16** [comment]
Should be fixed with [v1.6.0](https://github.com/Pictarine/macos-snippets/releases/tag/v1.6.0)
