### ISSUE TITLE
Can't install on Mac OS Catalina ?

### ISSUE THREAD

**Issue by mickaelperrin** [Pictarine/macos-snippets#15]
Hi,

I tried to install the app from the mac appstore, but it complains I don't have Mac OS 11 and refuses to install.

Is Snip only compatible with Big Sur ?

Thanks ,

**Comment by marshallino16** [comment]
Hey, 

You can install the previous version. 👌

**Comment by EdmundsEcho** [comment]
The app looks interesting.  Where can I access the version (1.4?) that works on OS 10.15?
