### ISSUE TITLE
Support for Laravel Blade syntax

### ISSUE THREAD

**Issue by manuels90** [Pictarine/macos-snippets#16]
Hi,

could you please add support for the [Laravel Blade](https://laravel.com/docs/8.x/blade) syntax? Would be much appreciated. Thanks for this amazing app. :-)

Kind regards
Manuel

**Comment by marshallino16** [comment]
Hi, 

I'm sorry but CodeMirror doesn't have a Laravel mode currently. 

[See here](https://discuss.codemirror.net/t/mode-for-laravel-blade/2655)

Feel free to reopen this issue if you find something.
