### ISSUE TITLE
Issue on MPB M1 Prozessor

### ISSUE THREAD

**Issue by delaadev** [Pictarine/macos-snippets#17]
If I enter quick some notes 
With Variables and Comments it looks like the app gets laggy.
And Hangsup

for. Example something like:

// Comment
var car
var bike
var etc

Then it begins instant zu Lag, the curser jumps to the first position an enter a "r" and removes instantly. 

![Bildschirmfoto 2021-02-03 um 17 10 51](https://user-images.githubusercontent.com/62119470/106775043-0bb22b80-6643-11eb-8123-e68e83b48396.png)
![Bildschirmfoto 2021-02-03 um 17 10 58](https://user-images.githubusercontent.com/62119470/106775049-0c4ac200-6643-11eb-8eec-6c41ccd3b84d.png)

**Comment by marshallino16** [comment]
Hey, 

Sorry for that. Yes, I need to work on the performances 🙏

I'll try to work on it next week

**Comment by marshallino16** [comment]
Next version is going to fix that. 👍

**Comment by marshallino16** [comment]
Should be fixed with [v1.6.0](https://github.com/Pictarine/macos-snippets/releases/tag/v1.6.0)
