### ISSUE TITLE
Fetch existing gists from github on connect

### ISSUE THREAD

**Issue by rafali** [Pictarine/macos-snippets#19]
It would be great to fetch existing gists when I connect my github action.
My main use case is that I use 2 computers and I would love to have my snippets in sync on both computers 🙏🏾

**Comment by rafali** [comment]
actually same as here: https://github.com/Pictarine/macos-snippets/issues/2

**Comment by marshallino16** [comment]
Should be fixed with [v1.6.0](https://github.com/Pictarine/macos-snippets/releases/tag/v1.6.0)
