### ISSUE TITLE
Github Gists

### ISSUE THREAD

**Issue by jwestbrook** [Pictarine/macos-snippets#2]
I found the way to push a code snippet to my GitHub Gists - but how do I pull my current gist "library" into Snip ?

**Comment by marshallino16** [comment]
Hi, 

Currently we don't pull existing Gists but that's definitively something we need to add 👍

**Comment by valentinocossar** [comment]
Hi, would be awesome also to keep Gists in sync. Now if I add a new Gist, when I delete it, Snip doesn't delete it from Github Gists and every time I click on the cloud icon to sync a Gist, Snip creates a new copy of that Gist on Github Gists.

**Comment by marshallino16** [comment]
Should be fixed with [v1.6.0](https://github.com/Pictarine/macos-snippets/releases/tag/v1.6.0)
