### ISSUE TITLE
show sidebar icon doesnt show up after relaunching the appp

### ISSUE THREAD

**Issue by palaniraja** [Pictarine/macos-snippets#21]
If user tapped the icon (hide sidebar) before quitting it. Relaunching doesn't have an option to bring back the sidebar

**Comment by marshallino16** [comment]
😱 Thanks, I will try to fix that today

**Comment by marshallino16** [comment]
Commit https://github.com/Pictarine/macos-snippets/commit/738ddf613cdb2059f3ca322b45e78b3f5b4cd7c1 will fix that.

This fix will be available in our next release.

**Comment by marshallino16** [comment]
New release [v1.7.0](https://github.com/Pictarine/macos-snippets/releases/tag/v1.7.0)
