### ISSUE TITLE
New snippet default language

### ISSUE THREAD

**Issue by jeaninem71** [Pictarine/macos-snippets#23]
Everytime I create a new snippet the default language is text, so I have to change it to Python. Is there a setting I am missing or can you tell me where I can change the default in the code so that new snippets are set to Python? Can you add a way to change the preferences using the menu please.

I enjoy your app and can't wait for the drag and drop feature. 

I would like to also request a sort by feature allowing to sort the folders and snippets within the folders by favorites at top, date added, alphabetically, etc.

**Comment by marshallino16** [comment]
Hi, 

Thanks for your feedback. 

The default mode can now be changed in the settings view (commit https://github.com/Pictarine/macos-snippets/commit/2cb35ba285a95e827bc3bf7133486673244e4e6e)

This feature will be available in out next release.

**Comment by marshallino16** [comment]
New release [v1.7.0](https://github.com/Pictarine/macos-snippets/releases/tag/v1.7.0)
