### ISSUE TITLE
Support for Semantic Web syntaxes

### ISSUE THREAD

**Issue by nishad** [Pictarine/macos-snippets#3]
Thanks a lot for this wonderful tool and making the source open.
It would be a great help, if there is support for semantic web syntaxes as well.

CodeMirror alrady supports [Turtle](https://codemirror.net/mode/turtle/index.html), [SPARQL](https://codemirror.net/mode/sparql/index.html) and [N-Triples](https://codemirror.net/mode/sparql/index.html), which are the major three syntaxes to make snippets part of essential semantic web toolkit.

**Comment by marshallino16** [comment]
Hi, 

I will add them today 👌

**Comment by marshallino16** [comment]
Fixed in https://github.com/Pictarine/macos-snippets/releases/tag/v1.4.0
