### ISSUE TITLE
Where are the snippets stored?

### ISSUE THREAD

**Issue by pw-64** [Pictarine/macos-snippets#32]
Are they in a json file? Where is the file or database where they are stored, so i can back them up or migrate between devices?

**Comment by MelodicCrypter** [comment]
Same question --- coz all of a sudden all my local added files were gone @marshallino16

**Comment by filip-komarzyniec** [comment]
Same question, any progress on that? Is there a local DB / file that I can upload onto my new device and restore my snippets? 

Rewriting all of them manually is definitely not an option 🫣

**Comment by mpaw** [comment]
@pw-64 @MelodicCrypter @filip-komarzyniec I think this app has been abandoned. But I was able to locate where it was writing all the snippet data. The folder you are looking for is:
```
~/Library/Containers/com.pictarine.Snip/Data/Library/Application Support/Snip
```
There is a `snippets` file in there that is just `JSON` and has an array of all your snippets. Easy to migrate them out of this app or to back them up.

**Comment by MelodicCrypter** [comment]
Thanks for the efforts... but all I saw there is the synched Github gists. But what I'm trying to restore is the older local snips. I couldn't recover them anymore. All of a sudden gone, local snips.

**Comment by filip-komarzyniec** [comment]
@MelodicCrypter --- building on the answer of @mpaw, in my case the exact location of the local snippets was: 
`~/Library/Containers/Snip/Data/Library/Application\ Support/Snip/snippets`. Hope that helps. 
My OSX version is: 13.6
