### ISSUE TITLE
Font size is stuck on 11

### ISSUE THREAD

**Issue by geochronology** [Pictarine/macos-snippets#4]
Not sure if this is a bug or a feature (I think it's a bug), but my font size is stuck on 11.

Furthermore, attempting to change the font settings in any **other** way is equally as fruitless a task. 

I attempted to make the change directly via inputs in the font menu (cmd-+, etc) and also tried via the Show Fonts dialog window.

Am I perhaps missing a way to activate the ability to make these edits?

I'm finding the app really fantastic otherwise. Keep up the amazing work!

**Comment by marshallino16** [comment]
Hi, 

Thank you for the feedback. 

Did you try the settings view? Bottom-left of the sidebar. 
You can change the font size there.

**Comment by geochronology** [comment]
It worked! That did the trick and the UI for it is nice too.

Good to know there's a workaround 😊
