### ISSUE TITLE
Feature request: right-click to add to folder

### ISSUE THREAD

**Issue by geochronology** [Pictarine/macos-snippets#6]
Hello, in one of my previous tickets I commented on the inability to drag and drop files into folders and you replied that this is due to a software limitation imposed by the current version of Mac OS.

In the meantime, and perhaps as an addition to the drag-and-drop feature that Big Sur will enable, I would like to propose a feature request of a right-click option prompting the user to add to folder. There should also be an option within this feature to return the file to the root directory if it's currently inside of a folder.

Thank you!

**Comment by marshallino16** [comment]
[Version 1.5.0](https://github.com/Pictarine/macos-snippets/releases/tag/v1.5.0) is out

Thank you for your contribution 👍
