### ISSUE TITLE
Feature request: make "+" button static when scrolling down

### ISSUE THREAD

**Issue by geochronology** [Pictarine/macos-snippets#7]
Currently when I scroll down on my list of gists, it hides the sidebar navigation (aka the + icon and the product logo). I think you should make these static so that I can access the + menu at any time.

**Comment by marshallino16** [comment]
Hey, 

It will be the case in the next update with all big sur / Xcode12.2 migration changes.

**Comment by marshallino16** [comment]
[Version 1.5.0](https://github.com/Pictarine/macos-snippets/releases/tag/v1.5.0) is out

Thank you for your contribution 👍
