### ISSUE TITLE
Allow php syntax highlighting without opening tags

### ISSUE THREAD

**Issue by carcam** [Pictarine/macos-snippets#8]
Right now when you have a php snippet, syntax highlighting only works if you add the *<?php* opening tag. Would it be possible to have Syntax highlighting for php snippets without adding the <?php tag?

**Comment by marshallino16** [comment]
Hey,

It will be the case in the next update with all big sur / Xcode12.2 migration changes.

**Comment by marshallino16** [comment]
[Version 1.5.0](https://github.com/Pictarine/macos-snippets/releases/tag/v1.5.0) is out

Thank you for your contribution 👍
